"""vision analyses, observations and calibrations

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 04:45:15.546108
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vision_calibrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("site_id", sa.String(length=36), nullable=True),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vision_calibrations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vision_calibrations_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vision_calibrations_project_id"), ["project_id"], unique=False)

    op.create_table(
        "vision_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("task", sa.Enum("PPE_HAZARD", "DEFECT", name="visiontask", native_enum=False), nullable=False),
        sa.Column("analyzer", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=60), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("preprocessing", sa.JSON(), nullable=False),
        sa.Column("image_quality", sa.JSON(), nullable=False),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vision_analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vision_analyses_evidence_id"), ["evidence_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vision_analyses_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vision_analyses_organization_id"), ["organization_id"], unique=False)

    op.create_table(
        "vision_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("above_threshold", sa.Boolean(), nullable=False),
        sa.Column("box", sa.JSON(), nullable=True),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("UNREVIEWED", "CONFIRMED", "REJECTED", name="observationreview", native_enum=False),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["vision_analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vision_observations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vision_observations_analysis_id"), ["analysis_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vision_observations_incident_id"), ["incident_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vision_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vision_observations_incident_id"))
        batch_op.drop_index(batch_op.f("ix_vision_observations_analysis_id"))

    op.drop_table("vision_observations")
    with op.batch_alter_table("vision_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vision_analyses_organization_id"))
        batch_op.drop_index(batch_op.f("ix_vision_analyses_incident_id"))
        batch_op.drop_index(batch_op.f("ix_vision_analyses_evidence_id"))

    op.drop_table("vision_analyses")
    with op.batch_alter_table("vision_calibrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vision_calibrations_project_id"))
        batch_op.drop_index(batch_op.f("ix_vision_calibrations_organization_id"))

    op.drop_table("vision_calibrations")
    # ### end Alembic commands ###
