"""Drive one incident through the whole product workflow over HTTP and write a Markdown results report.

Usage:
    python scripts/demo_walkthrough.py --base-url http://localhost:8000 --out docs/RESULTS.md

Requires the API running with demo seed data (SITEGUARD_SEED_DEMO_DATA=true).
"""

import argparse
import os
from datetime import UTC, datetime

import httpx

PASSWORD = os.environ.get("SITEGUARD_DEMO_PASSWORD", "siteguard-demo")
PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 128  # placeholder image bytes for the demo upload


class Api:
    def __init__(self, base: str):
        self.http = httpx.Client(base_url=base, timeout=120)
        self.tokens: dict[str, str] = {}

    def as_(self, who: str) -> dict:
        if who not in self.tokens:
            r = self.http.post("/auth/login", json={"email": f"{who}@demo.siteguard.local", "password": PASSWORD})
            r.raise_for_status()
            self.tokens[who] = r.json()["data"]["access_token"]
        return {"Authorization": f"Bearer {self.tokens[who]}"}

    def call(self, method: str, path: str, who: str, **kw):
        r = self.http.request(method, path, headers=self.as_(who), **kw)
        if r.status_code >= 400:
            raise SystemExit(f"{method} {path} as {who} -> {r.status_code}: {r.text}")
        return r.json()["data"]


def table(rows: list[list], head: list[str]) -> str:
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c).replace("|", "/") for c in r) + " |" for r in rows]
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default="http://localhost:8000")
    ap.add_argument("--out", default="docs/RESULTS.md")
    args = ap.parse_args()
    api = Api(args.base_url)
    md: list[str] = []
    health = api.http.get("/health").json()["data"]
    project = next(p for p in api.call("GET", "/projects", "pm") if p["code"] == "RMT-01")
    pid = project["id"]
    before = api.call("GET", "/dashboard", "pm", params={"project_id": pid})

    md += [
        "# Site Guard AI: pilot results",
        "",
        f"Generated by `scripts/demo_walkthrough.py` against a running API on "
        f"{datetime.now(UTC):%d %B %Y %H:%M} UTC. AI provider: `{health['ai_provider']}`.",
        "",
        "All incidents are **synthetic** (see `data/seed/incidents.yaml`) and the knowledge base is synthetic site "
        "procedures (see `data/seed/knowledge/`). The numbers below are produced by the real API, agents, risk "
        "engine and workflow, not typed by hand.",
        "",
        f"## 1. Project dashboard before the walkthrough ({project['name']})",
        "",
        table([[k.replace("_", " "), v] for k, v in before["totals"].items()], ["Metric", "Value"]),
        "",
        "Incidents by status: " + ", ".join(f"{k} {v}" for k, v in sorted(before["by_status"].items())),
        "",
        "Top hazards found by triage: " + ", ".join(f"{h} ({n})" for h, n in before["top_hazards"]),
        "",
    ]

    # A new incident reported from site.
    inc = api.call("POST", f"/projects/{pid}/incidents", "site", json={
        "title": "Worker fell from mobile scaffold tower in level 2 corridor",
        "description": "A drywall installer fell about 2 m from a mobile scaffold tower. The tower had no guardrail "
        "on one side and was not tagged as inspected. He was not wearing a harness. He was taken to hospital with a "
        "suspected wrist fracture.",
        "domain": "SAFETY", "severity": "HIGH", "occurred_at": datetime.now(UTC).isoformat(),
        "location": "Tower A, level 2 corridor", "activity": "Ceiling installation", "people_involved": 1,
        "immediate_actions": "First aid, ambulance called, tower quarantined, area barricaded.",
    })
    iid = inc["id"]
    api.http.post(f"/incidents/{iid}/evidence", headers=api.as_("site"),
                  files={"file": ("scene.png", PNG, "image/png")},
                  data={"description": "Scaffold tower platform with missing guardrail on the open side"})
    md += [f"## 2. New incident {inc['reference']}", "", f"> **{inc['title']}**  ", f"> {inc['description']}", ""]

    res = api.call("POST", f"/incidents/{iid}/investigate", "safety")
    runs = {r["agent"]: r for r in res["runs"]}
    tri = runs["triage"]["output"]
    md += [
        "## 3. Multi-agent investigation",
        "",
        table([[r["agent"], r["provider"], r["status"], "yes" if r["needs_human_review"] else "no",
                len([t for t in r["trace"] if t["type"] == "tool_call"])] for r in res["runs"]],
              ["Agent", "Provider", "Status", "Flagged for review", "Tool calls"]),
        "",
        f"**Triage:** {tri['incident_class']} / {tri['domain']} / severity {tri['severity_candidate']} / "
        f"priority {tri['priority']} / confidence {tri['confidence']}.  ",
        f"Hazards: {', '.join(tri['hazards'])}.  ",
        f"Missing information: {'; '.join(tri['missing_information']) or 'none'}.",
        "",
    ]
    if "safety" in runs:
        s = runs["safety"]["output"]
        md += ["**Safety investigation:**", "", f"- Unsafe acts: {'; '.join(s['unsafe_acts'])}",
               f"- Unsafe conditions: {'; '.join(s['unsafe_conditions'])}",
               f"- Failed or missing controls: {'; '.join(s['failed_or_missing_controls'])}", ""]
    md += [f"**Deterministic risk:** {res['risk']['rationale']}", ""]
    rca = runs["rca"]["output"]
    md += ["**Root cause analysis (5-Whys):**", ""] + [f"{i}. {w}" for i, w in enumerate(rca["whys"], 1)] + [""]
    md += [table([[c["category"], c["statement"], c["confidence"]] for c in rca["root_causes"]],
                 ["Category", "Root cause hypothesis", "Confidence"]), ""]
    comp = runs["compliance"]["output"]
    md += ["**Compliance mapping (retrieved requirements, cited):**", "",
           table([[f["status"], f["requirement"][:110], f["source_title"]] for f in comp["findings"]],
                 ["Status", "Requirement", "Source"]), "", f"_{comp['disclaimer']}_", ""]
    md += ["**Proposed actions (all PENDING_REVIEW until a human decides):**", "",
           table([[a["action_type"], a["title"], a["owner_role"], a["due_date"], a["verification_criteria"]]
                  for a in res["proposed_actions"]], ["Type", "Action", "Owner", "Due", "Verification"]), ""]
    if res["flags"]:
        md += ["Flags: " + " ".join(res["flags"]), ""]

    # Human decisions.
    actions = res["proposed_actions"]
    blocked = api.http.post(f"/incidents/{iid}/close", headers=api.as_("hse"), json={"note": "try"})
    pm_try = api.http.post(f"/capa/{actions[0]['id']}/review", headers=api.as_("pm"),
                           json={"decision": "APPROVE", "reason": "ok"})
    md += ["## 4. Human approval and guardrails", "",
           f"- Closing before review: HTTP {blocked.status_code}, `{blocked.json()['error']['code']}`: "
           f"{blocked.json()['error']['message']}",
           f"- Project manager approving a critical (HIGH-risk) action: HTTP {pm_try.status_code}, "
           f"`{pm_try.json()['error']['code']}`. Only the HSE manager can.", ""]
    keep, drop = actions[:3], actions[3:]
    for a in keep:
        api.call("POST", f"/capa/{a['id']}/review", "hse", json={"decision": "APPROVE", "reason": "Proportionate"})
    for a in drop:
        api.call("POST", f"/capa/{a['id']}/review", "hse",
                 json={"decision": "REJECT", "reason": "Covered by the approved actions"})
    site_id = api.call("GET", "/me", "site")["id"]
    for a in keep:
        api.call("PATCH", f"/capa/{a['id']}/progress", "site",
                 json={"work_status": "COMPLETED", "assignee_id": site_id, "note": "Done"})
    self_verify = api.http.post(f"/capa/{keep[0]['id']}/verify", headers=api.as_("site"),
                                json={"effective": True, "notes": "mine"})
    for a in keep:
        api.call("POST", f"/capa/{a['id']}/verify", "safety",
                 json={"effective": True, "notes": "Checked on site; control in place."})
    closed = api.call("POST", f"/incidents/{iid}/close", "pm", json={"note": "All actions verified effective."})
    ws = api.call("GET", f"/incidents/{iid}", "hse")
    md += [f"- HSE manager approved {len(keep)} action(s) and rejected {len(drop)} with reasons.",
           f"- Site engineer verifying their own work: HTTP {self_verify.status_code} "
           f"(`{self_verify.json()['error']['code']}`).",
           f"- Safety engineer verified {len(ws['verifications'])} action(s); project manager closed the incident: "
           f"status **{closed['status']}**.", "",
           "## 5. Lifecycle history", "",
           table([[h["created_at"][:19], h["from_status"] or "", h["to_status"], h["note"] or ""]
                  for h in ws["history"]], ["Time (UTC)", "From", "To", "Note"]), ""]
    audit = api.call("GET", "/audit", "auditor", params={"entity_id": iid})
    md += [f"Audit events on this incident: {len(audit)} (every one carries a correlation ID).", ""]

    after = api.call("GET", "/dashboard", "pm", params={"project_id": pid})
    md += ["## 6. Dashboard after the walkthrough", "",
           table([[k.replace("_", " "), before["totals"][k], v] for k, v in after["totals"].items()],
                 ["Metric", "Before", "After"]), "",
           "Agent runs: " + ", ".join(f"{k} {v}" for k, v in after["agents"].items() if k != "providers"), ""]

    with open(args.out, "w") as fh:
        fh.write("\n".join(md))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
